

DROP TABLE IF EXISTS public."ExpressionOfInterest";

CREATE TABLE IF NOT EXISTS public."ExpressionOfInterest" (
    "Id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "PageName" VARCHAR(255) NOT NULL,
    "UserName" VARCHAR(255) NOT NULL,
    "UserEmail" VARCHAR(255) NOT NULL,
    "UserBusinessName" VARCHAR(255) NULL,
    "UserPhone" VARCHAR(255) NULL,
	"OptInMarketingEmail" BOOL NOT NULL DEFAULT FALSE,
    "OptInMarketingPhone" BOOL NOT NULL DEFAULT FALSE,
    "OptInReadPrivacy" BOOL NOT NULL DEFAULT FALSE,
    "RecordCreatedUtc" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    CONSTRAINT "PK_ExpressionOfInterest" PRIMARY KEY ("Id")
);

